//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edesoft.ERP.Domain.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ativos
    {
        public System.Guid Id { get; set; }
        public string Codigo { get; set; }
        public string Nome { get; set; }
        public System.Guid SetorId { get; set; }
        public System.Guid SubSetorId { get; set; }
        public string Logotipo { get; set; }
    
        public virtual Setores Setores { get; set; }
        public virtual SubSetores SubSetores { get; set; }
    }
}
