//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edesoft.ERP.Domain.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CEP
    {
        public System.Guid Id { get; set; }
        public string NrCep { get; set; }
        public System.Guid IdCidade { get; set; }
        public string Logradouro { get; set; }
        public string Bairro { get; set; }
        public int CodigoIBGE { get; set; }
    
        public virtual Cidade Cidade { get; set; }
    }
}
