//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edesoft.ERP.Domain.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EdesoftDataBaseEntities : DbContext
    {
        public EdesoftDataBaseEntities()
            : base("name=EdesoftDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ativos> Ativos { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Contratante> Contratante { get; set; }
        public virtual DbSet<ContratanteModules> ContratanteModules { get; set; }
        public virtual DbSet<Corporacao> Corporacao { get; set; }
        public virtual DbSet<Modules> Modules { get; set; }
        public virtual DbSet<Perfis> Perfis { get; set; }
        public virtual DbSet<PerfisRoles> PerfisRoles { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RoleModules> RoleModules { get; set; }
        public virtual DbSet<Setores> Setores { get; set; }
        public virtual DbSet<SubSetores> SubSetores { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<CEP> CEP { get; set; }
        public virtual DbSet<Cidade> Cidade { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<UF> UF { get; set; }
    }
}
