//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edesoft.ERP.Domain.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfisRoles
    {
        public System.Guid IdPerfil { get; set; }
        public System.Guid IdRole { get; set; }
        public bool CanPost { get; set; }
        public bool CanPut { get; set; }
        public bool CanDelete { get; set; }
        public bool CanGet { get; set; }
    
        public virtual Perfis Perfis { get; set; }
        public virtual Role Role { get; set; }
    }
}
