//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edesoft.ERP.Domain.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Role()
        {
            this.PerfisRoles = new HashSet<PerfisRoles>();
            this.Role1 = new HashSet<Role>();
            this.RoleModules = new HashSet<RoleModules>();
        }
    
        public System.Guid Id { get; set; }
        public double InternalRoleId { get; set; }
        public Nullable<System.Guid> IdParentRole { get; set; }
        public string Name { get; set; }
        public string Icon { get; set; }
        public string Slug { get; set; }
        public string Hash { get; set; }
        public double OrdMenu { get; set; }
        public bool Ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerfisRoles> PerfisRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Role1 { get; set; }
        public virtual Role Role2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleModules> RoleModules { get; set; }
    }
}
